# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20170906_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudent',
            name='student',
            field=models.ManyToManyField(related_name='course', to=settings.AUTH_USER_MODEL, verbose_name='选课学生'),
        ),
    ]
