# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20170907_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.TextField(blank=True, default='', null=True, verbose_name='课程简介'),
        ),
    ]
