# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('number', models.CharField(max_length=15, unique=True, verbose_name='学号')),
                ('role', models.CharField(choices=[(1, '学生'), (2, '教师'), (3, '教务员')], default=1, max_length=1, verbose_name='角色')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('address', models.CharField(max_length=100, verbose_name='居住地址')),
                ('birthday', models.DateField(null=True, verbose_name='出生年月')),
                ('mobile', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='超级用户')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理员')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
    ]
