# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='学号'),
        ),
    ]
