# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170903_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailValidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('code', models.CharField(max_length=16, verbose_name='验证码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', '学生'), ('2', '教师'), ('3', '教务员')], default=1, max_length=1, verbose_name='角色'),
        ),
    ]
